os:
  - linux
  - osx
  - windows

language: go

go:
  # "1.x" always refers to the latest Go version, inc. the patch release.
  # e.g. "1.x" is 1.13 until 1.13.1 is available.
  - 1.13.x
  - 1.14.x
  - tip

matrix:
  allow_failures:
    - os: windows
      go: tip

install:
  - go get -d -v ./...

script:
  - go build -v ./...
  - go test ./...